@startuml
left to right direction
skinparam packageStyle rectangle

rectangle "Báo cáo số liệu chi nhánh" {
  usecase "Chọn kỳ báo cáo" as UC1
  usecase "Xem số liệu" as UC2
  usecase "Xuất file" as UC3

  usecase "Thời gian không hợp lệ" as Ex1
  usecase "Không có dữ liệu" as Ex2
  usecase "Lỗi sinh file" as Ex3
}

UC2 ..> Ex1 : <<extend>>
UC2 ..> Ex2 : <<extend>>
UC3 ..> Ex3 : <<extend>>
@enduml
